changelog:
  exclude:
    labels:
      - release
    authors:
      - octocat
  categories:
    - title: 【機能】
      labels:
        - "Type: enhancement"
        - "Type: feature"
    - title: 【改善】
      labels:
        - improvement
        - fix
    - title: 【開発関係】
      labels:
        - development
        - chore
    - title: 【その他】
      labels:
        - "*"
