name: Create Release PR

on:
  push:
    tags:
      # 数字だけで構成されてるタグ( = release)
      - '\d\.\d\.\d'

jobs:
  build:
    name: create release PR
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get commit diff summary
        id: get_previous_tag
        run: |
          PREVIOUS_TAG=$(git tag --sort=-creatordate | grep -E '^[0-9]*\.[0-9]*\.[0-9]*' | sed -n 2p)
          echo "PREVIOUS_TAG: $PREVIOUS_TAG"
          echo ::set-output name=PREVIOUS_TAG::$PREVIOUS_TAG

      # - name: generate release note
      #   id: get_release_note
      #   uses: actions/github-script@v4.0.2
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       return "**Full Changelog**: https://github.com/0eta0/test-ga-create-release-pr/compare/0.2.9...0.3.0"

      # - name: create PR to master from develop
      #   uses: actions/github-script@v4.0.2
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       github.pulls.create({
      #         ...context.repo,
      #         head: "develop",
      #         base: "master",
      #         title: "release v${{github.ref_name}} to master",
      #         body: "${{steps.get_release_note.outputs.result}}"
      #       });

      - name: create PR to master from develop
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.pulls.create({
              ...context.repo,
              head: "develop",
              base: "master",
              title: "release v${{github.ref_name}} to master",
              body: "**Full Changelog**: https://github.com/0eta0/test-ga-create-release-pr/compare/0.2.9...0.3.0"
            });
